# Generated by Django 4.0.3 on 2022-03-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=300)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
