# Generated by Django 4.0.3 on 2022-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_empleados_fecha_nacimiento_pacientes_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='fecha',
        ),
        migrations.AddField(
            model_name='empleados',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
