# Generated by Django 4.0.3 on 2022-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_remove_empleados_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.CharField(max_length=300)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
