# Generated by Django 4.0.3 on 2022-04-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0006_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
