# Generated by Django 4.0.3 on 2022-04-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0010_alter_page_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
    ]
