# Generated by Django 4.0.3 on 2022-04-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0011_alter_page_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
