# Generated by Django 4.0.3 on 2022-05-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0014_post_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
